import { useEffect, useState, useCallback, useMemo } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { motion } from 'framer-motion';
import {
  FileText, Download, Printer, Briefcase, ArrowLeft, ChevronRight, Loader2, FileJson,
} from 'lucide-react';
import { getCases, getReport } from '../services/api';
import RiskBadge from '../components/RiskBadge';
import StatusBadge from '../components/StatusBadge';
import PageTransition from '../components/PageTransition';
import LoadingSpinner from '../components/LoadingSpinner';
import ErrorState from '../components/ErrorState';
import EmptyState from '../components/EmptyState';
import { formatCurrency, formatDateTime } from '../utils/format';

/**
 * Investigation report — the final, evidence-backed output of a case.
 *
 * Every section is generated by the backend Report Agent from the same records
 * the agents used, so the document is reproducible and traceable. Wording stays
 * neutral: risk indicators, not accusations.
 */

const SEVERITY_COLOR = {
  CRITICAL: 'text-red-400 border-red-500/30 bg-red-500/5',
  HIGH: 'text-orange-400 border-orange-500/30 bg-orange-500/5',
  MEDIUM: 'text-amber-400 border-amber-500/30 bg-amber-500/5',
  LOW: 'text-sky-400 border-sky-500/30 bg-sky-500/5',
  INFO: 'text-surface-400 border-surface-700 bg-surface-800/40',
};

const factorLabel = (t) =>
  String(t || '')
    .toLowerCase()
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');

function Section({ n, title, subtitle, children, className = '' }) {
  return (
    <section className={`break-inside-avoid ${className}`}>
      <div className="flex items-baseline gap-2.5 mb-3 pb-2 border-b border-surface-800">
        <span className="text-[10px] font-mono font-bold text-accent-400 bg-accent-500/10 border border-accent-500/25 rounded px-1.5 py-0.5 shrink-0">
          {String(n).padStart(2, '0')}
        </span>
        <div className="min-w-0">
          <h3 className="text-sm font-bold text-white tracking-wide print:text-black">{title}</h3>
          {subtitle && <p className="text-[10px] text-surface-500 mt-0.5 print:text-gray-600">{subtitle}</p>}
        </div>
      </div>
      {children}
    </section>
  );
}

function Field({ label, value, mono = false }) {
  if (value === null || value === undefined || value === '') return null;
  return (
    <div className="min-w-0">
      <p className="text-[10px] font-bold uppercase tracking-widest text-surface-500 print:text-gray-500">{label}</p>
      <p className={`text-xs text-surface-200 mt-0.5 break-words print:text-black ${mono ? 'font-mono' : ''}`}>{value}</p>
    </div>
  );
}

function FieldGrid({ children, cols = 'sm:grid-cols-2 lg:grid-cols-3' }) {
  return <div className={`grid grid-cols-1 ${cols} gap-3`}>{children}</div>;
}

function DownloadJson({ data, filename }) {
  const download = () => {
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
  };
  return (
    <button onClick={download} className="btn-secondary py-2 px-3 text-xs" title="Download the full report data as JSON">
      <FileJson className="w-3.5 h-3.5" />
      Export JSON
    </button>
  );
}

export default function Reports() {
  const [searchParams, setSearchParams] = useSearchParams();
  const selectedId = searchParams.get('case');
  const [cases, setCases] = useState([]);
  const [listLoading, setListLoading] = useState(true);
  const [listError, setListError] = useState(null);
  const [report, setReport] = useState(null);
  const [reportLoading, setReportLoading] = useState(false);
  const [reportError, setReportError] = useState(null);

  const loadCases = useCallback(async () => {
    setListLoading(true);
    try {
      const res = await getCases();
      setCases(res.data);
      setListError(null);
    } catch (err) {
      setListError(err.message);
    } finally {
      setListLoading(false);
    }
  }, []);

  useEffect(() => {
    loadCases();
  }, [loadCases]);

  const loadReport = useCallback(async (caseId) => {
    if (!caseId) {
      setReport(null);
      return;
    }
    setReportLoading(true);
    try {
      const res = await getReport(caseId);
      setReport(res.data);
      setReportError(null);
    } catch (err) {
      setReport(null);
      setReportError(err.message);
    } finally {
      setReportLoading(false);
    }
  }, []);

  useEffect(() => {
    loadReport(selectedId);
  }, [selectedId, loadReport]);

  const select = (caseId) => {
    if (caseId) setSearchParams({ case: caseId });
    else setSearchParams({});
  };

  const printableCases = useMemo(
    () => cases.filter((c) => (c.agentCount || 0) > 0 || c.riskScore),
    [cases]
  );

  // ------------------------------------------------------------------ picker
  if (!selectedId) {
    return (
      <PageTransition>
        <div className="p-6 lg:p-8 max-w-[1600px] mx-auto space-y-5">
          <div>
            <h1 className="text-2xl font-extrabold text-white flex items-center gap-2.5">
              <FileText className="w-6 h-6 text-accent-400" />
              Investigation Reports
            </h1>
            <p className="text-xs text-surface-400 mt-1 leading-relaxed">
              Evidence-backed case reports. Every section is generated from the case record — findings, risk
              assessment, evidence, and the human decision.
            </p>
          </div>

          <div className="card p-0 overflow-hidden">
            {listLoading ? (
              <LoadingSpinner text="Loading cases…" />
            ) : listError ? (
              <ErrorState error={listError} onRetry={loadCases} title="Cases unavailable" />
            ) : printableCases.length === 0 ? (
              <EmptyState
                icon={FileText}
                title="No reports available"
                description="Run an investigation on a case, then return here to generate its report."
                action={
                  <Link to="/cases" className="btn-primary py-2 px-3.5 text-xs">
                    <Briefcase className="w-3.5 h-3.5" /> Open case inventory
                  </Link>
                }
              />
            ) : (
              <div className="divide-y divide-surface-800/50">
                {printableCases.map((c, i) => (
                  <motion.button
                    key={c.caseId}
                    initial={{ opacity: 0, y: 6 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: Math.min(i, 12) * 0.03 }}
                    onClick={() => select(c.caseId)}
                    className="w-full flex items-center justify-between gap-4 px-4 py-3.5 hover:bg-surface-800/30 transition-colors text-left"
                  >
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-2 flex-wrap">
                        <span className="font-mono text-sm font-bold text-accent-400">{c.caseId}</span>
                        <span className="font-mono text-[11px] text-surface-500">{c.customerId}</span>
                        <span className="font-mono text-[11px] text-surface-500">{c.transactionId}</span>
                      </div>
                      <p className="text-[11px] text-surface-400 mt-1">
                        {formatCurrency(c.amount)} • {c.evidenceCount || 0} evidence item(s) • opened{' '}
                        {formatDateTime(c.createdAt)}
                      </p>
                    </div>
                    <div className="flex items-center gap-2 shrink-0">
                      <RiskBadge level={c.riskLevel} />
                      <StatusBadge status={c.status} />
                      <ChevronRight className="w-4 h-4 text-surface-500" />
                    </div>
                  </motion.button>
                ))}
              </div>
            )}
          </div>
        </div>
      </PageTransition>
    );
  }

  // ------------------------------------------------------------------ report
  return (
    <PageTransition>
      <div className="p-6 lg:p-8 max-w-[1100px] mx-auto space-y-5">
        <div className="flex flex-wrap items-center justify-between gap-3 no-print">
          <button onClick={() => select(null)} className="text-xs text-surface-400 hover:text-accent-400 flex items-center gap-1.5 transition-colors">
            <ArrowLeft className="w-3.5 h-3.5" /> All reports
          </button>
          <div className="flex flex-wrap items-center gap-2">
            <Link to={`/cases/${selectedId}`} className="btn-secondary py-2 px-3 text-xs">
              <Briefcase className="w-3.5 h-3.5" /> Open case
            </Link>
            <DownloadJson data={report} filename={`${selectedId}-report.json`} />
            <button onClick={() => window.print()} className="btn-primary py-2 px-3 text-xs">
              <Printer className="w-3.5 h-3.5" /> Print / Save PDF
            </button>
          </div>
        </div>

        {reportLoading ? (
          <div className="card flex items-center justify-center min-h-[40vh]">
            <LoadingSpinner text="Generating report…" />
          </div>
        ) : reportError ? (
          <div className="card max-w-lg mx-auto">
            <ErrorState error={reportError} onRetry={() => loadReport(selectedId)} title="Report unavailable" />
          </div>
        ) : !report ? (
          <div className="card">
            <EmptyState icon={FileText} title="No report data" />
          </div>
        ) : (
          <article className="card print:bg-white print:border-0 print:shadow-none print:p-0 space-y-6">
            {/* Document header */}
            <header className="flex flex-wrap items-start justify-between gap-4 pb-4 border-b border-surface-800 print:border-gray-300">
              <div>
                <p className="text-[10px] font-bold uppercase tracking-widest text-accent-400 print:text-gray-600">
                  FraudLens — Investigation Report
                </p>
                <h1 className="text-xl font-extrabold text-white font-mono mt-1 print:text-black">{report.caseId}</h1>
                <p className="text-[11px] text-surface-400 mt-1 print:text-gray-600">
                  Generated {formatDateTime(report.generatedAt)} • cycle {report.investigationCycles}
                </p>
              </div>
              <div className="flex flex-col items-end gap-1.5">
                <span className="text-[10px] uppercase tracking-widest text-surface-500 print:text-gray-500">Risk Assessment</span>
                <div className="flex items-center gap-2">
                  <span className="text-xl font-bold text-white font-mono print:text-black">
                    {report.riskAssessment?.score}
                    <span className="text-xs text-surface-500 print:text-gray-500">/100</span>
                  </span>
                  <RiskBadge level={report.riskAssessment?.level} />
                </div>
                <StatusBadge status={report.status} />
              </div>
            </header>

            {/* 01 Case Information */}
            <Section n={1} title="Case Information" subtitle="Identifiers and workflow state">
              <FieldGrid>
                <Field label="Case ID" value={report.caseInformation?.caseId || report.caseId} mono />
                <Field label="Alert ID" value={report.caseInformation?.alertId} mono />
                <Field label="Status" value={report.caseInformation?.status?.replace(/_/g, ' ')} />
                <Field label="Investigation Cycles" value={report.caseInformation?.investigationCycles} />
                <Field label="Opened" value={formatDateTime(report.caseInformation?.openedAt)} />
                <Field label="Last Updated" value={formatDateTime(report.caseInformation?.lastUpdated)} />
                {report.caseInformation?.focusAreas?.length > 0 && (
                  <Field label="Deep-Dive Areas" value={report.caseInformation.focusAreas.join(', ')} mono />
                )}
              </FieldGrid>
            </Section>

            {/* 02 Executive Summary */}
            <Section n={2} title="Executive Summary" subtitle="Grounded narrative composed from case evidence">
              <p className="text-sm text-surface-200 leading-relaxed print:text-black">{report.executiveSummary}</p>
            </Section>

            {/* 03 Transaction */}
            <Section n={3} title="Transaction Under Investigation" subtitle="Subject transaction record">
              <FieldGrid>
                <Field label="Transaction ID" value={report.transaction?.transactionId} mono />
                <Field label="Customer ID" value={report.transaction?.customerId} mono />
                <Field label="Amount" value={formatCurrency(report.transaction?.amount)} mono />
                <Field label="Type" value={report.transaction?.transactionType?.replace(/_/g, ' ')} />
                <Field label="Merchant" value={report.transaction?.merchant} />
                <Field label="Location" value={report.transaction?.location} />
                <Field label="Device" value={report.transaction?.deviceId} mono />
                <Field label="Timestamp" value={formatDateTime(report.transaction?.timestamp)} />
                <Field label="Transaction Status" value={report.transaction?.status} />
              </FieldGrid>
            </Section>

            {/* 04 Customer */}
            <Section n={4} title="Customer Profile" subtitle="Recorded account baseline">
              <FieldGrid>
                <Field label="Customer ID" value={report.customer?.customerId} mono />
                <Field label="Name" value={report.customer?.name} />
                <Field label="Account Age" value={report.customer?.accountAge} />
                <Field label="Average Transaction" value={formatCurrency(report.customer?.averageTransactionAmount)} mono />
                <Field label="Usual Locations" value={(report.customer?.usualLocations || []).join(', ')} />
                <Field label="Usual Devices" value={(report.customer?.usualDevices || []).join(', ')} mono />
                <Field label="Usual Hours" value={(report.customer?.usualTransactionHours || []).join(', ')} mono />
              </FieldGrid>
            </Section>

            {/* 05 Behaviour */}
            <Section n={5} title="Behavioural Analysis" subtitle="Transaction compared against the 90-day baseline">
              <FieldGrid>
                <Field label="Historical Transactions" value={report.behaviourAnalysis?.historicalCount} />
                <Field label="Historical Average" value={formatCurrency(report.behaviourAnalysis?.historicalAverage)} mono />
                <Field label="Declared Average" value={formatCurrency(report.behaviourAnalysis?.declaredAverage)} mono />
                <Field
                  label="Deviation Ratio"
                  value={report.behaviourAnalysis?.ratio ? `${report.behaviourAnalysis.ratio}×` : null}
                  mono
                />
                <Field label="Transaction Hour" value={report.behaviourAnalysis?.transactionHour} />
                <Field label="Usual Hours" value={(report.behaviourAnalysis?.usualHours || []).join(', ')} mono />
              </FieldGrid>
              {report.behaviourAnalysis?.findings?.length > 0 && (
                <ul className="mt-3 space-y-1">
                  {report.behaviourAnalysis.findings.map((f) => (
                    <li key={f.evidenceId} className="text-[11px] text-surface-300 flex items-start gap-2 print:text-black">
                      <span className="font-mono text-accent-400 shrink-0 print:text-gray-600">{f.evidenceId}</span>
                      <span>{f.description}</span>
                    </li>
                  ))}
                </ul>
              )}
            </Section>

            {/* 06 Location */}
            <Section n={6} title="Location Analysis" subtitle="Geo-spatial comparison">
              <FieldGrid>
                <Field label="Transaction Location" value={report.locationAnalysis?.current} />
                <Field label="Usual Locations" value={(report.locationAnalysis?.usual || []).join(', ')} />
                <Field label="Outside Usual Pattern" value={report.locationAnalysis?.isUnusual ? 'Yes' : 'No'} />
                <Field label="Recent Locations" value={(report.locationAnalysis?.recentLocations || []).join(', ')} />
              </FieldGrid>
              {report.locationAnalysis?.findings?.length > 0 && (
                <ul className="mt-3 space-y-1">
                  {report.locationAnalysis.findings.map((f) => (
                    <li key={f.evidenceId} className="text-[11px] text-surface-300 flex items-start gap-2 print:text-black">
                      <span className="font-mono text-accent-400 shrink-0 print:text-gray-600">{f.evidenceId}</span>
                      <span>{f.description}</span>
                    </li>
                  ))}
                </ul>
              )}
            </Section>

            {/* 07 Device */}
            <Section n={7} title="Device Analysis" subtitle="Device fingerprint and account linkage">
              <FieldGrid>
                <Field label="Device ID" value={report.deviceAnalysis?.deviceId} mono />
                <Field label="New for Customer" value={report.deviceAnalysis?.isNewForCustomer ? 'Yes' : 'No'} />
                <Field label="Associated Customers" value={(report.deviceAnalysis?.associatedCustomers || []).join(', ')} mono />
                <Field label="Related Customers" value={(report.deviceAnalysis?.relatedCustomers || []).join(', ')} mono />
                <Field label="Previous Cases" value={(report.deviceAnalysis?.previousCases || []).join(', ')} mono />
                <Field label="Previous Alerts" value={(report.deviceAnalysis?.previousAlerts || []).join(', ')} mono />
                <Field label="Transactions on Device" value={report.deviceAnalysis?.transactionCount} />
                <Field label="First Seen" value={formatDateTime(report.deviceAnalysis?.firstSeen)} />
                <Field label="Last Seen" value={formatDateTime(report.deviceAnalysis?.lastSeen)} />
              </FieldGrid>
              {report.deviceAnalysis?.findings?.length > 0 && (
                <ul className="mt-3 space-y-1">
                  {report.deviceAnalysis.findings.map((f) => (
                    <li key={f.evidenceId} className="text-[11px] text-surface-300 flex items-start gap-2 print:text-black">
                      <span className="font-mono text-accent-400 shrink-0 print:text-gray-600">{f.evidenceId}</span>
                      <span>{f.description}</span>
                    </li>
                  ))}
                </ul>
              )}
            </Section>

            {/* 08 Risk Assessment */}
            <Section n={8} title="Risk Assessment" subtitle="Deterministic rule sum — not a probability">
              <div className="space-y-2">
                {(report.riskAssessment?.factors || []).map((f, i) => (
                  <div
                    key={`${f.type}-${i}`}
                    className="flex items-start justify-between gap-3 p-2.5 rounded-lg bg-surface-800/40 border border-surface-800 print:bg-gray-50 print:border-gray-200"
                  >
                    <div className="min-w-0 flex-1">
                      <p className="text-xs font-semibold text-white print:text-black">{factorLabel(f.type)}</p>
                      {f.description && <p className="text-[11px] text-surface-400 mt-0.5 print:text-gray-700">{f.description}</p>}
                      {f.evidenceIds?.length > 0 && (
                        <p className="text-[10px] font-mono text-accent-400 mt-1 print:text-gray-600">
                          {f.evidenceIds.join(', ')}
                        </p>
                      )}
                    </div>
                    <span className="text-sm font-mono font-bold text-amber-400 shrink-0 print:text-black">+{f.weight}</span>
                  </div>
                ))}
              </div>
              <p className="text-[11px] text-surface-500 mt-3 print:text-gray-600">
                Total: {report.riskAssessment?.score}/100 ({report.riskAssessment?.level}). {report.riskAssessment?.note}
              </p>
            </Section>

            {/* 09 Evidence */}
            <Section n={9} title="Evidence Register" subtitle={`${report.evidence?.length || 0} item(s) recorded by the analysis agents`}>
              <div className="space-y-1.5">
                {(report.evidence || []).map((ev) => (
                  <div
                    key={ev.evidenceId}
                    className={`flex items-start gap-2.5 p-2.5 rounded-lg border ${SEVERITY_COLOR[ev.severity] || SEVERITY_COLOR.INFO} print:border-gray-200 print:bg-white`}
                  >
                    <span className="font-mono text-[10px] font-bold text-accent-400 shrink-0 mt-0.5 print:text-gray-700">
                      {ev.evidenceId}
                    </span>
                    <div className="min-w-0 flex-1">
                      <p className="text-xs text-surface-200 leading-relaxed print:text-black">{ev.description}</p>
                      <p className="text-[10px] text-surface-500 mt-0.5 font-mono print:text-gray-500">
                        {ev.type} • {ev.severity} • {ev.source}
                      </p>
                    </div>
                  </div>
                ))}
                {(!report.evidence || report.evidence.length === 0) && (
                  <p className="text-xs text-surface-500 print:text-gray-600">No evidence recorded.</p>
                )}
              </div>
            </Section>

            {/* 10 Agent Findings */}
            <Section n={10} title="Agent Findings" subtitle="What each agent concluded">
              <div className="space-y-1.5">
                {(report.agentFindings || []).map((a, i) => (
                  <div key={`${a.agent}-${i}`} className="p-2.5 rounded-lg bg-surface-800/40 border border-surface-800 print:bg-gray-50 print:border-gray-200">
                    <div className="flex items-center justify-between gap-2">
                      <p className="text-xs font-bold text-white print:text-black">{a.agent}</p>
                      <div className="flex items-center gap-2">
                        <span className="text-[10px] font-mono text-surface-500 print:text-gray-600">{a.duration}ms</span>
                        <span className="text-[10px] font-mono text-surface-400 print:text-gray-600">{a.status}</span>
                      </div>
                    </div>
                    {a.summary && <p className="text-[11px] text-surface-300 mt-1 leading-relaxed print:text-black">{a.summary}</p>}
                    {a.evidenceIds?.length > 0 && (
                      <p className="text-[10px] font-mono text-accent-400 mt-1 print:text-gray-600">{a.evidenceIds.join(', ')}</p>
                    )}
                  </div>
                ))}
              </div>
            </Section>

            {/* 11 Relationship Findings */}
            <Section
              n={11}
              title="Relationship Findings"
              subtitle={`${report.relationshipFindings?.nodeCount || 0} entities, ${report.relationshipFindings?.edgeCount || 0} relationships — discovered from the database`}
            >
              <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">
                <div>
                  <p className="text-[10px] font-bold uppercase tracking-widest text-surface-500 mb-1.5 print:text-gray-500">
                    Entities
                  </p>
                  <ul className="space-y-0.5">
                    {(report.relationshipFindings?.nodes || []).map((n) => (
                      <li key={n.id} className="text-[11px] text-surface-300 flex items-center gap-2 print:text-black">
                        <span className="font-mono text-[9px] uppercase text-surface-500 shrink-0 print:text-gray-600">
                          {n.type}
                        </span>
                        <span className="truncate">{n.label}</span>
                        {n.sublabel && <span className="font-mono text-[10px] text-surface-500 shrink-0">({n.sublabel})</span>}
                      </li>
                    ))}
                  </ul>
                </div>
                <div>
                  <p className="text-[10px] font-bold uppercase tracking-widest text-surface-500 mb-1.5 print:text-gray-500">
                    Relationships
                  </p>
                  <ul className="space-y-0.5">
                    {(report.relationshipFindings?.edges || []).map((e, i) => (
                      <li key={i} className="text-[11px] text-surface-300 font-mono print:text-black">
                        {e.source} <span className="text-surface-500">→</span> {e.target}
                        {e.label && <span className="text-surface-500"> ({e.label})</span>}
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </Section>

            {/* 12 Additional Investigation */}
            {report.additionalInvestigation && (
              <Section n={12} title="Additional Investigation" subtitle="Focused deep-dive requested by the investigator">
                <FieldGrid cols="sm:grid-cols-2 lg:grid-cols-3">
                  {(report.additionalInvestigation.areas || []).map((a) => (
                    <Field key={a.area} label={a.label} value={`${a.recordCount} record(s) — ${a.note}`} />
                  ))}
                </FieldGrid>
                <p className="text-[11px] text-surface-500 mt-2 font-mono print:text-gray-600">
                  {report.additionalInvestigation.totalRecords} record(s) examined in total.
                </p>
              </Section>
            )}

            {/* 13 Human Review */}
            <Section n={13} title="Human Review" subtitle="Investigator decision — final authority">
              {report.humanDecision?.action ? (
                <div className="p-3 rounded-xl border border-sky-500/30 bg-sky-500/5 print:border-gray-300 print:bg-white">
                  <FieldGrid cols="sm:grid-cols-2 lg:grid-cols-4">
                    <Field label="Decision" value={report.humanDecision.action.replace(/_/g, ' ')} />
                    <Field label="Reviewer" value={report.humanDecision.decidedBy} />
                    <Field label="Timestamp" value={formatDateTime(report.humanDecision.decidedAt)} />
                    {report.humanDecision.areas?.length > 0 && (
                      <Field label="Areas Requested" value={report.humanDecision.areas.join(', ')} mono />
                    )}
                  </FieldGrid>
                  {report.humanDecision.note && (
                    <p className="text-xs text-surface-200 mt-2.5 leading-relaxed print:text-black">
                      <span className="text-surface-500 print:text-gray-600">Notes: </span>
                      {report.humanDecision.note}
                    </p>
                  )}
                </div>
              ) : (
                <p className="text-xs text-amber-400 bg-amber-500/10 border border-amber-500/30 rounded-lg px-3 py-2 print:bg-white print:border-gray-300 print:text-black">
                  HUMAN INVESTIGATION REQUIRED — no investigator decision has been recorded on this case.
                </p>
              )}

              <div className="mt-4 p-3 rounded-xl bg-accent-500/5 border border-accent-500/25 print:bg-white print:border-gray-300">
                <p className="text-[10px] font-bold uppercase tracking-widest text-accent-400 mb-1 print:text-gray-600">
                  Recommendation
                </p>
                <p className="text-xs text-surface-200 leading-relaxed print:text-black">{report.recommendation}</p>
              </div>
            </Section>

            {/* Audit trail */}
            {report.auditTimeline?.length > 0 && (
              <Section n="A" title="Audit Timeline" subtitle="Agent execution order">
                <ol className="space-y-1">
                  {report.auditTimeline.map((a, i) => (
                    <li key={i} className="flex items-start gap-2.5 text-[11px] print:text-black">
                      <span className="font-mono text-surface-500 shrink-0 print:text-gray-600">
                        {String(i + 1).padStart(2, '0')}
                      </span>
                      <span className="font-semibold text-surface-200 shrink-0 w-32 truncate print:text-black">{a.agent}</span>
                      <span className="text-surface-400 flex-1">{a.summary}</span>
                    </li>
                  ))}
                </ol>
              </Section>
            )}

            <footer className="pt-4 border-t border-surface-800 print:border-gray-300">
              <p className="text-[10px] text-surface-600 leading-relaxed print:text-gray-600">
                Generated by FraudLens from synthetic demonstration data. Risk scoring uses a configurable
                deterministic rule set and is not a universal financial risk standard. Recorded outcomes describe
                risk indicators only and do not constitute a finding of wrongdoing against any customer.
              </p>
            </footer>
          </article>
        )}
      </div>
    </PageTransition>
  );
}
